appId: com.ledebe.protector
productName: Ledebe Protector
files:
  - dist/**
  - index.prod.html
  - src/**/*
  - package.json
extraMetadata:
  main: dist/main.js

mac:
  target:
    - dmg
  category: public.app-category.productivity
  icon: assets/icon.icns
  hardenedRuntime: true
  gatekeeperAssess: true
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.inherit.plist

dmg:
  background: build/dmg_background.png
  icon: assets/icon.icns
  iconSize: 128
  window:
    width: 600
    height: 400

win:
  target:
    - nsis
  icon: assets/icon.ico

nsis:
  oneClick: false
  allowElevation: true
  allowToChangeInstallationDirectory: false
  createDesktopShortcut: always
  createStartMenuShortcut: true
  shortcutName: "Ledebe Protector"
  runAfterFinish: true
  deleteAppDataOnUninstall: false

linux:
  target:
    - AppImage
  category: Utility
